### PR TITLE
#using official python 3.11

### PR DESCRIPTION
**Pull request by P1ro**
oficcial Python version 
remove python versions from workflow

### CODE REVIEW

**Comment by P1ro** [comment]
Minors changes for the workflow

**Comment by tomasohara** [comment]
Thanks. I forgot to comment on this. I need to hold off on the python version issue. For this particular repo, the Bash script tests are more critical (e.g., for alias testing).

**Comment by tomasohara** [comment]
By the way, I'm looking into enabling the python matrix in the workflow yaml files for Github only. I made changes to the wrong repo, but I figured I might as well try it here. (The shell-scripts repo workflow is too slow locally with just one python version!) Anyway, thanks for your observations.

**Comment by P1ro** [comment]
Sure, let me know where and when you want to start, I might be a bit busy
this week.

**Comment by tomasohara** [comment]
That was an FYI: I'm doing it myself.

Best,
Tom

**Comment by tomasohara** [comment]
Something like this will be done later this year as with need to address Python 3.12 as well: stay tuned.

**Comment by P1ro** [comment]
Great, sure, also if need some testing let me know.

**Pull request closed without merging**
